global:
  scrape_interval: 5s
  evaluation_interval: 30s
scrape_configs:
  - job_name: server-scraper
    honor_labels: true
    static_configs:
      - targets: ["python-application:5000", "python-application:6000"]
